#!/usr/bin/env bash

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

python3 -m pip install --user --upgrade pynvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
#install ripgrep otherwise the grep wont return anything
sudo apt-get install ripgrep

for f in `find . -regex ".*\.vim$\|.*\.lua$" -printf '%f\n'`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/phyu/plugin/$f ~/.config/nvim/$f
done
