#!/usr/bin/env bash
sudo ln -s /usr/local/bin/nvim /usr/local/bin/vim

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.vim/{autoload,colors,doc}
sonokai_path=~/.local/share/nvim/site/sonokai

echo $sonokai_path


git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
git clone https://github.com/sainnhe/sonokai.git ${sonokai_path}

cp ${sonokai_path}/autoload/sonokai.vim ~/.vim/autoload/.
cp ${sonokai_path}/colors/sonokai.vim ~/.vim/colors/.
cp ${sonokai_path}/docs/sonokai.txt ~/.vim/doc/.

python3 -m pip install --user --upgrade pynvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
#install ripgrep otherwise the grep wont return anything
sudo apt-get install ripgrep

for f in `find ./nvim -name "*.vim" -or -name "*.lua"`; do
	x=$(echo $f | cut -f3 -d '/');
	rm -rf ~/.config/nvim/$x
	ln -s ~/dotfiles/phyu/nvim/$x ~/.config/nvim/$x 
done
